//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxChatLauncher.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobloxChatLauncher.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Roblox Chat Launcher:
        ///Made with ❤︎ by Riri and Contributors
        ///Developed in VS 2026 🎀 Built with .NET / WinForms
        ///Server written in Node.js 🌸 Hosted on Render.com and Neon.com
        ///Source: https://github.com/RobloxChatLauncher/RobloxChatLauncher
        ///And of course, credits to you 💖.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎀 Account linked successfully!.
        /// </summary>
        public static string AccountLinked {
            get {
                return ResourceManager.GetString("AccountLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already up to date ({0}).
        /// </summary>
        public static string AlreadyUpToDate {
            get {
                return ResourceManager.GetString("AlreadyUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to log in....
        /// </summary>
        public static string AttemptingLogin {
            get {
                return ResourceManager.GetString("AttemptingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press / key | Ctrl+Shift+C to hide.
        /// </summary>
        public static string ChatInputBoxText {
            get {
                return ResourceManager.GetString("ChatInputBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Code not found. Please check your profile and ensure you requested the correct username..
        /// </summary>
        public static string CodeNotFound {
            get {
                return ResourceManager.GetString("CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected successfully!.
        /// </summary>
        public static string ConnectedSuccessfully {
            get {
                return ResourceManager.GetString("ConnectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server {0}....
        /// </summary>
        public static string ConnectingToServer {
            get {
                return ResourceManager.GetString("ConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error: {0}.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: {0}.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a valid Roblox Client..
        /// </summary>
        public static string CouldNotFindClient {
            get {
                return ResourceManager.GetString("CouldNotFindClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any releases..
        /// </summary>
        public static string CouldNotFindReleases {
            get {
                return ResourceManager.GetString("CouldNotFindReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open link: {0}.
        /// </summary>
        public static string CouldNotOpenLink {
            get {
                return ResourceManager.GetString("CouldNotOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Channel ID.
        /// </summary>
        public static string CurrentChannelID {
            get {
                return ResourceManager.GetString("CurrentChannelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===================================================.
        /// </summary>
        public static string DebugConsoleHorizontalRule {
            get {
                return ResourceManager.GetString("DebugConsoleHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG CONSOLE INITIALIZED AT {0}.
        /// </summary>
        public static string DebugConsoleInitialized {
            get {
                return ResourceManager.GetString("DebugConsoleInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Chat Launcher Debugger.
        /// </summary>
        public static string DebugConsoleTitle {
            get {
                return ResourceManager.GetString("DebugConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;/console&apos; or &apos;/debug&apos; again to close.
        /// </summary>
        public static string DebugConsoleUseClose {
            get {
                return ResourceManager.GetString("DebugConsoleUseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update ({0} → {1})....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Only you can see this message.).
        /// </summary>
        public static string EchoResponse {
            get {
                return ResourceManager.GetString("EchoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote error: {0}.
        /// </summary>
        public static string EmoteError {
            get {
                return ResourceManager.GetString("EmoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to queue emote..
        /// </summary>
        public static string FailedToQueueEmote {
            get {
                return ResourceManager.GetString("FailedToQueueEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message: {0}.
        /// </summary>
        public static string FailedToSendMessage {
            get {
                return ResourceManager.GetString("FailedToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching code for {0}....
        /// </summary>
        public static string FetchingCode {
            get {
                return ResourceManager.GetString("FetchingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current message filter: {0}.
        /// </summary>
        public static string FilterPreferenceCurrent {
            get {
                return ResourceManager.GetString("FilterPreferenceCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message filter set to: {0}.
        /// </summary>
        public static string FilterPreferenceSet {
            get {
                return ResourceManager.GetString("FilterPreferenceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Could not read your device ID. Please restart the launcher and try again..
        /// </summary>
        public static string HardwareIdFailed {
            get {
                return ResourceManager.GetString("HardwareIdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update... The app will close shortly..
        /// </summary>
        public static string InstallingUpdate {
            get {
                return ResourceManager.GetString("InstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be installed when you close the app.
        ///Chat &apos;/update&apos; to install it now..
        /// </summary>
        public static string ItWillBeInstalled {
            get {
                return ResourceManager.GetString("ItWillBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher registered. ({0}).
        /// </summary>
        public static string LauncherRegistered {
            get {
                return ResourceManager.GetString("LauncherRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered! The next time you launch a game from the Roblox website, the chat overlay will start automatically..
        /// </summary>
        public static string LauncherRegisteredBalloonText {
            get {
                return ResourceManager.GetString("LauncherRegisteredBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Chat Launcher.
        /// </summary>
        public static string LauncherRegisteredBalloonTitle {
            get {
                return ResourceManager.GetString("LauncherRegisteredBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local data cleared. (Server sync may have failed)..
        /// </summary>
        public static string LocalDataCleared {
            get {
                return ResourceManager.GetString("LocalDataCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out..
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Verification failed due to a server error..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! Login successful..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Message hidden due to your filter settings.].
        /// </summary>
        public static string MessageHiddenDueToFilterSettings {
            get {
                return ResourceManager.GetString("MessageHiddenDueToFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message could not be processed due to a server error. Please try again..
        /// </summary>
        public static string MessageRejectedApiError {
            get {
                return ResourceManager.GetString("MessageRejectedApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was not sent as it violates community guidelines..
        /// </summary>
        public static string MessageRejectedModeration {
            get {
                return ResourceManager.GetString("MessageRejectedModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was rejected because the server queue is full. Please try again shortly..
        /// </summary>
        public static string MessageRejectedQueueFull {
            get {
                return ResourceManager.GetString("MessageRejectedQueueFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was not sent due to unknown reasons..
        /// </summary>
        public static string MessageRejectedUnknown {
            get {
                return ResourceManager.GetString("MessageRejectedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be verified to use /emote..
        /// </summary>
        public static string MustBeVerifiedEmote {
            get {
                return ResourceManager.GetString("MustBeVerifiedEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker &apos;{0}&apos; has been muted..
        /// </summary>
        public static string MutedSpeaker {
            get {
                return ResourceManager.GetString("MutedSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account linked to this device. Use /verify &lt;username&gt; to start..
        /// </summary>
        public static string NoAccountLinked {
            get {
                return ResourceManager.GetString("NoAccountLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stable releases found. Use &apos;/update prerelease&apos; to check for alpha/beta versions..
        /// </summary>
        public static string NoStableReleases {
            get {
                return ResourceManager.GetString("NoStableReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening website....
        /// </summary>
        public static string OpeningWebsite {
            get {
                return ResourceManager.GetString("OpeningWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write registry key: {0}.
        /// </summary>
        public static string RegistryWriteFailed {
            get {
                return ResourceManager.GetString("RegistryWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out. (Render server may be waking up).
        /// </summary>
        public static string RequestTimedOut {
            get {
                return ResourceManager.GetString("RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved Roblox Client: {0} ({1}).
        /// </summary>
        public static string ResolvedClientInfo {
            get {
                return ResourceManager.GetString("ResolvedClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored registry to: {0}.
        /// </summary>
        public static string RestoredRegistry {
            get {
                return ResourceManager.GetString("RestoredRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running from source; update skipped..
        /// </summary>
        public static string RunningFromSource {
            get {
                return ResourceManager.GetString("RunningFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Please run /verify &lt;username&gt; first!.
        /// </summary>
        public static string RunVerifyFirst {
            get {
                return ResourceManager.GetString("RunVerifyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker &apos;{0}&apos; was not muted..
        /// </summary>
        public static string SpeakerNotMuted {
            get {
                return ResourceManager.GetString("SpeakerNotMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with ❤︎ by Riri and Contributors
        ///Chat &apos;/?&apos; or &apos;/help&apos; for a list of chat commands..
        /// </summary>
        public static string StartupText {
            get {
                return ResourceManager.GetString("StartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching server....
        /// </summary>
        public static string SwitchingServer {
            get {
                return ResourceManager.GetString("SwitchingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command &apos;{0}&apos;. Use &apos;/?&apos; or &apos;/help&apos; for a list of commands..
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlinking your Roblox account and clearing local data....
        /// </summary>
        public static string UnlinkingAccount {
            get {
                return ResourceManager.GetString("UnlinkingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker &apos;{0}&apos; has been unmuted..
        /// </summary>
        public static string UnmutedSpeaker {
            get {
                return ResourceManager.GetString("UnmutedSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Successfully unverified. You are now a Guest..
        /// </summary>
        public static string UnverifiedSuccess {
            get {
                return ResourceManager.GetString("UnverifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed: {0}.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /emote &lt;name&gt;.
        /// </summary>
        public static string UsageEmote {
            get {
                return ResourceManager.GetString("UsageEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /filter &lt;strict|default|relaxed&gt;.
        /// </summary>
        public static string UsageFilter {
            get {
                return ResourceManager.GetString("UsageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /mute &lt;speaker&gt;.
        /// </summary>
        public static string UsageMute {
            get {
                return ResourceManager.GetString("UsageMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /unmute &lt;speaker&gt;.
        /// </summary>
        public static string UsageUnmute {
            get {
                return ResourceManager.GetString("UsageUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /verify &lt;RobloxUsername&gt;.
        /// </summary>
        public static string UsageVerify {
            get {
                return ResourceManager.GetString("UsageVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: /w &quot;&lt;speaker 12345&gt;&quot; message or /w &lt;speaker&gt; message.
        /// </summary>
        public static string UsageWhisper {
            get {
                return ResourceManager.GetString("UsageWhisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not found in this channel..
        /// </summary>
        public static string UserNotFoundInChannel {
            get {
                return ResourceManager.GetString("UserNotFoundInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Verification failed due to a server error..
        /// </summary>
        public static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Code copied: {0}
        ///2. Paste it into your Roblox Profile &apos;About&apos; section.
        ///3. Type /confirm to finish.
        ///Your code will expire in 10 minutes..
        /// </summary>
        public static string VerifyStepsText {
            get {
                return ResourceManager.GetString("VerifyStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0}.
        /// </summary>
        public static string WhisperFrom {
            get {
                return ResourceManager.GetString("WhisperFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0}.
        /// </summary>
        public static string WhisperTo {
            get {
                return ResourceManager.GetString("WhisperTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket not connected. Use &apos;/rc&apos; or &apos;/reconnect&apos; to connect to server..
        /// </summary>
        public static string WSNotConnected {
            get {
                return ResourceManager.GetString("WSNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Receive Error: {0}.
        /// </summary>
        public static string WSReceiveError {
            get {
                return ResourceManager.GetString("WSReceiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Send Error: {0}.
        /// </summary>
        public static string WSSendError {
            get {
                return ResourceManager.GetString("WSSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS send timed out. (Render server may be waking up).
        /// </summary>
        public static string WSSendTimedOut {
            get {
                return ResourceManager.GetString("WSSendTimedOut", resourceCulture);
            }
        }
    }
}
