name: Bump Integrations Submodule 

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Pull Latest Submodule Commit
        id: check
        run: |
          git submodule update --init --recursive
          OLD_SHA=$(git rev-parse --short HEAD:integrations) # Current tracked SHA
          
          # Pull the latest remote updates for integrations
          git submodule update --remote integrations
          NEW_SHA=$(git -C integrations rev-parse --short HEAD)

          if [ "$NEW_SHA" != "$OLD_SHA" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "old_sha=$OLD_SHA" >> $GITHUB_OUTPUT
            echo "new_sha=$NEW_SHA" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(integrations): bump integrations submodule from ${{ steps.check.outputs.old_sha }} to ${{ steps.check.outputs.new_sha }}" 
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          title: "chore(integrations): bump integrations submodule from ${{ steps.check.outputs.old_sha }} to ${{ steps.check.outputs.new_sha }}" 
          body: |
            Bumps the integrations submodule reference from commit ${{ steps.check.outputs.old_sha }} to ${{ steps.check.outputs.new_sha }}. 
          labels: |
            area:integrations 
            github_actions
          branch: chore/bump-integrations-submodule
          delete-branch: true
