name: Bump Dependencies in Installer

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 5 * * 1" # Every Monday at 5:00 AM UTC
  workflow_dispatch:

jobs:
  bump-dependencies:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6

    - name: Get current .NET version from Installer.iss
      id: current
      run: |
        CURRENT_VER=$(sed -n 's/^#define DotNetVersion "\([^"]*\)".*/\1/p' installer/Installer.iss)
        echo "version=$CURRENT_VER" >> $GITHUB_OUTPUT

    - name: Fetch latest .NET 10.0 Runtime version
      id: latest
      run: |
        VERSION=$(curl -s https://builds.dotnet.microsoft.com/dotnet/release-metadata/releases-index.json | \
                  jq -r '.["releases-index"][] | select(."channel-version"=="10.0") | ."latest-release"')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Compare local and latest versions
      id: check
      run: |
        CURRENT="${{ steps.current.outputs.version }}"
        LATEST="${{ steps.latest.outputs.version }}"

        if [ "$CURRENT" != "$LATEST" ] && dpkg --compare-versions "$LATEST" gt "$CURRENT"; then
          echo "is_newer=true" >> $GITHUB_OUTPUT
        else
          echo "is_newer=false" >> $GITHUB_OUTPUT
        fi

    - name: Replace .NET version in Installer.iss
      if: steps.check.outputs.is_newer == 'true'
      run: |
        sed -i "s/^\(#define DotNetVersion \)\"[^\"]*\"/\1\"${{ steps.latest.outputs.version }}\"/" installer/Installer.iss

    - name: Create Pull Request
      if: steps.check.outputs.is_newer == 'true'
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore(deps): bump .NET Desktop Runtime link from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }}"
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: true
        title: "chore(deps): bump .NET Desktop Runtime link from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }}"
        body: |
          Bumps .NET Desktop Runtime link in installer from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }}.
        labels: |
          dependencies
          github_actions
        branch: installer/dotnet-runtime
        delete-branch: true
        draft: false
